### ISSUE TITLE
cdvd register 0x0B reflects tray state, should reflect media changed status

### ISSUE THREAD

**Issue by fldef** [fldef/pcsx2-fldef#1]
This is incorrect:

https://github.com/fldef/pcsx2-fldef/blob/715672481b1c61a4ce8da76c71dbac06aaf68d60/pcsx2/CDVD/CDVD.cpp#L1056-L1063

See also:

https://github.com/fldef/pcsx2-fldef/blob/715672481b1c61a4ce8da76c71dbac06aaf68d60/pcsx2/CDVD/CDVD.cpp#L1499-L1505

**Comment by fldef** [comment]
@seta-san If you're feeling bold, try the (unofficial) bug fix I have here:

https://github.com/fldef/pcsx2-fldef/releases/tag/v1.6.0-swapfix-0

It's just an updated `pcsx2.exe` with the swap fix for SingStar. If you do try it, let me know if it works!

**Comment by seta-san** [comment]
> f you're feeling bold, try the (unofficial) bug fix I have here:
> 
> [https://github.com/fldef/pcsx2-fldef/releases](https://github.com/fldef/pcsx2-fldef/releases/tag/v1.6.0-swapfix-0)

i just tried it. didn't work

**Comment by fldef** [comment]
Thanks for trying it out. SingStar's swap problem must be something different.

**Comment by seta-san** [comment]
> Thanks for trying it out. SingStar's swap problem must be something different.

You can feel free to keep trying

**Comment by fldef** [comment]
As time allows I'll keep digging into this.

Which USB plugin do you use for the microphone? Are you using a SingStar mic or something else?

**Comment by seta-san** [comment]
> As time allows I'll keep digging into this.
> 
> Which USB plugin do you use for the microphone? Are you using a SingStar mic or something else?

Yes. I'm using singstar mic and qemu usb plugin

**Comment by fldef** [comment]
The original problem is fixed, so I'll close this issue. I've documented the SingStar problem under bug #2.
